### ISSUE TITLE
[Feature Request] add share shortcuts in Finder sidebar

### ISSUE THREAD

**Issue by dotbreak** [monkeydri/nas-automount#1]
The generated app (nas-automount.app) should add shortcuts to the shares created in the Finder sidebar. There should be an option (true by default) to activate this behaviour from the generator app (generate-nas-automount-app.app).

**Comment by capsudo** [comment]
Optional Finder sidebar shortcut creation added in commit 94d9560f4ecaef3495e0153d0e1fd92479c06944.

The shortcuts are not added by default, user who runs the generated app will be asked if he wants shortcuts to be created or not (default being no). However this behaviour can be overridden by "forcing" the shortcut creation. This is done on app generation (answer yes to the dialog).
